### ISSUE TITLE
vgo2nix doesn't find all dependencies for Hugo

### ISSUE THREAD

**Issue by sondr3** [nix-community/vgo2nix#14]
In nixos/nixpkgs#55915 I wanted to update Hugo to the latest version, but ran into an issue where two dependencies weren't included in the `deps.nix` file, so I had to manually write them myself and hope that they worked, you can see them in the top of the dependencies file. I was wondering if you had any ideas as to why it wouldn't find them? I ran `vgo2nix` from the latest release on master because of #13.

**Comment by adisbladis** [comment]
What I _think_ is going on here has to do with the upstream use of the `replace` directive in go.mod: https://github.com/gohugoio/hugo/blob/v0.54.0/go.mod#L64.
`inflect` removed their dependency on `envy`, but `replace` pulls in a version of `inflect` that still depends on `envy`.

**Comment by sondr3** [comment]
Would you consider this a bug/missing feature in vgo2nix or something that is actually possible to resolve automatically? I got asked about this in my pull request 😃

**Comment by adisbladis** [comment]
I think it's a bug in go modules and/or upstream packaging.
There is no circumstance which should result in a dependency missing from `go.sum`.

**Comment by sondr3** [comment]
Alright, thanks for the help :smiley:

**Comment by SuperSandro2000** [comment]
@Mic92 can be closed, too.
