### ISSUE TITLE
respect go.mod's replace operator

### ISSUE THREAD

**Issue by flokli** [nix-community/vgo2nix#22]
From https://github.com/NixOS/nixpkgs/pull/62432#discussion_r289618118

> Looks like vgo2nix doesn't respect go.mod's replace operator. Shouldn't be an issue in this case, but it is notable.

**Comment by zx2c4** [comment]
Some more details, which might help. Consider this go.mod:

```
require github.com/Microsoft/go-winio v0.4.12
replace github.com/Microsoft/go-winio => golang.zx2c4.com/wireguard/windows v0.0.0-20190429060359-b01600290cd4
```

What this is says is, "replace all references to github.com/Microsoft/go-winio with the repo at golang.zx2c4.com/wireguard/windows checked out to revision v0.0.0-20190429060359-b01600290cd4." Right, now, however, vgo2nix ignores the replace part.

**Comment by Vskilet** [comment]
I've the same problem for building mautrix-whatsapp bridge

**Comment by Vskilet** [comment]
Is there someone who found a workaround ?

**Comment by mikroskeem** [comment]
Any updates on this?

**Comment by mikroskeem** [comment]
#27

**Comment by SuperSandro2000** [comment]
@Mic92 can be closed, too.
