### ISSUE TITLE
Version suffixes not included in goPackagePath

### ISSUE THREAD

**Issue by charles-dyfis-net** [nix-community/vgo2nix#30]
See the reproducer at https://gist.github.com/charles-dyfis-net/c5762f9ed5cdd3c91e4c67f11f141d5a (feel free to `git clone` it to run yourself).

Given the following `go.mod`:

```
module testGoModule

go 1.13

require github.com/pion/dtls/v2 v2.0.0-rc.5
```

`vgo2nix` generates a `deps.nix` containing the following entry:

```
  {
    goPackagePath = "github.com/pion/dtls";
    fetch = {
      type = "git";
      url = "https://github.com/pion/dtls";
      rev = "v2.0.0-rc.5";
      sha256 = "0zp038i61kmsr2mik471vi5c67lk3hyw8yp5lajjw4s4ghxplm2q";
    };
  }
```

...which is faulty, as the `goPackagePath` *should* be `github.com/pion/dtls/v2` for the build to succeed.

**Comment by SuperSandro2000** [comment]
@Mic92 this should be fixed also. Can be closed.
